theme: jekyll-theme-slate

# Name of website
title: mluker.com

# Short description of your site
description: ""

show_downloads: false

github:
  is_project_page: false
  repository_url: ""

exclude:  
  - README.md
