# Site settings
title: Matt Luker
url: 'https://www.mluker.com'
baseurl: ''
profilepic: '/images/headshot.jpeg'
bkimage: '/images/bk1s.jpg'
font_awesome: 'b07c42aced.js'

author:
  name: 'Matt Luker'
  email: luker.matt@gmail.com  
  # twitter_username: mluker
  github_username:  mluker
  linkedin_username:  matt-luker

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']


